export default {
  "$neutralColorLowPure": "#000000",
  "$neutralColorLowLight": "#8E9199",
  "$neutralColorLowMedium": "#5E6066",
  "$neutralColorLowDark": "#2D2E33",
  "$neutralColorHighPure": "#FFFFFF",
  "$neutralColorHighLight": "#F2F4F7",
  "$neutralColorHighMedium": "#E4E5EB",
  "$neutralColorHighDark": "#C0C3CC",
  "$neutralColorOpacityLowDarkSemiOpaque": "rgba(45, 46, 51, 0.72)",
  "$neutralColorOpacityLowDarkIntense": "rgba(45, 46, 51, 0.56)",
  "$neutralColorOpacityLowDarkMedium": "rgba(45, 46, 51, 0.32)",
  "$neutralColorOpacityLowDarkLight": "rgba(45, 46, 51, 0.16)",
  "$neutralColorOpacityLowDarkSemiTransparent": "rgba(45, 46, 51, 0.08)",
  "$neutralColorOpacityHighLightSemiOpaque": "rgba(242, 244, 247, 0.72)",
  "$neutralColorOpacityHighLightIntense": "rgba(242, 244, 247, 0.56)",
  "$neutralColorOpacityHighLightMedium": "rgba(242, 244, 247, 0.32)",
  "$neutralColorOpacityHighLightLight": "rgba(242, 244, 247, 0.16)",
  "$neutralColorOpacityHighLightSemiTransparent": "rgba(242, 244, 247, 0.08)",
  "$brandColorPrimaryPure": "#288542",
  "$brandColorPrimaryLight": "#CFFAC8",
  "$brandColorPrimaryMedium": "#63B85E",
  "$brandColorPrimaryDark": "#00652E",
  "$brandColorSecondaryPure": "#8DC63F",
  "$brandColorSecondaryLight": "#DEF5BF",
  "$brandColorSecondaryMedium": "#ABD66F",
  "$brandColorSecondaryDark": "#77AD2D",
  "$categoryColorMyDiscountPure": "#3EBDAC",
  "$categoryColorFidelityFirstPure": "#3EBDAC",
  "$categoryColorFidelityFirstLight": "#BFF5EE",
  "$categoryColorFidelityFirstMedium": "#76D6C9",
  "$categoryColorFidelityFirstDark": "#1D9988",
  "$categoryColorFidelitySecondPure": "#9E945C",
  "$categoryColorFidelitySecondLight": "#D9D2AD",
  "$categoryColorFidelitySecondMedium": "#80753C",
  "$categoryColorFidelitySecondDark": "#615722",
  "$categoryColorFidelityThirdPure": "#000000",
  "$categoryColorFidelityThirdLight": "#8E9199",
  "$categoryColorFidelityThirdMedium": "#5E6066",
  "$categoryColorFidelityThirdDark": "#2D2E33",
  "$categoryColorStixPure": "#9341F1",
  "$categoryColorStixLight": "#D0AAFD",
  "$categoryColorStixMedium": "#631BB6",
  "$categoryColorStixDark": "#16074A",
  "$categoryColorMarketplacePure": "#009FE3",
  "$categoryColorMarketplaceLight": "#C2EDFF",
  "$categoryColorMarketplaceMedium": "#337AB7",
  "$categoryColorMarketplaceDark": "#1B4873",
  "$highlightColorPure": "#FAB914",
  "$highlightColorLight": "#FFF0C2",
  "$highlightColorMedium": "#FFCE47",
  "$highlightColorDark": "#EB981C",
  "$feedbackColorPositivePure": "#288542",
  "$feedbackColorPositiveLight": "#CFFAC8",
  "$feedbackColorPositiveMedium": "#62B85E",
  "$feedbackColorPositiveDark": "#00652E",
  "$feedbackColorDestructivePure": "#BE0013",
  "$feedbackColorDestructiveLight": "#FFC2C8",
  "$feedbackColorDestructiveMedium": "#F54556",
  "$feedbackColorDestructiveDark": "#8F000E",
}